backend:
  name: github
  repo: <你的GitHub用户名>/<你的仓库名>
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "home"
    label: "首页内容"
    files:
      - file: "index.html"
        label: "首页"
        name: "index"
        fields:
          - { label: "主标题", name: "hero_title", widget: "string" }
          - { label: "副标题", name: "hero_subtitle", widget: "string" }
          - { label: "按钮文字", name: "hero_button", widget: "string" }
  - name: "services"
    label: "服务"
    files:
      - file: "index.html"
        label: "服务"
        name: "services"
        fields:
          - { label: "服务列表", name: "service_list", widget: "list", fields: [ {label: "服务名称", name: "title", widget: "string"}, {label: "描述", name: "desc", widget: "string"} ] }
  - name: "team"
    label: "团队"
    files:
      - file: "index.html"
        label: "团队"
        name: "team"
        fields:
          - { label: "团队成员", name: "members", widget: "list", fields: [ {label: "姓名", name: "name", widget: "string"}, {label: "职位", name: "role", widget: "string"}, {label: "简介", name: "desc", widget: "string"} ] }
  - name: "contact"
    label: "联系方式"
    files:
      - file: "index.html"
        label: "联系方式"
        name: "contact"
        fields:
          - { label: "地址", name: "address", widget: "string" }
          - { label: "电话", name: "phone", widget: "string" }
          - { label: "邮箱", name: "email", widget: "string" }